apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-sync
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/lihao2000B/GitOpsAdminRepo.git
  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-sync
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/dev
  prune: true
  serviceAccountName: user
  sourceRef:
    kind: GitRepository
    name: flux-sync
