---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: user
  namespace: gitops-demo
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/lihao2000B/GitOpsUserRepo.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: user
  namespace: gitops-demo
spec:
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: user

